os: linux
language: c++
dist: trusty
group: stable
sudo: required
notifications:
  email:
    on_success: never
    on_failure: never
services:
  - mysql
  - postfix
  - memcached
env:
  - MATRIX_EVAL="COMPILER=gcc-4.8 CC=gcc-4.8 CXX=g++-4.8 TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-4.9 CC=gcc-4.9 CXX=g++-4.9 TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-5 CC=gcc-5 CXX=g++-5 TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-6 CC=gcc-6 CXX=g++-6 TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-7 CC=gcc-7 CXX=g++-7 TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-8 CC=gcc-8 CXX=g++-8 TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-4.8 FLAGS='-DMAGMA_PEDANTIC -O0' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-4.8 FLAGS='-DMAGMA_PEDANTIC -O2' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-4.8 FLAGS='-DMAGMA_PEDANTIC -O3' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-4.8 FLAGS='-UMAGMA_PEDANTIC -O0' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-4.8 FLAGS='-UMAGMA_PEDANTIC -O2' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-4.8 FLAGS='-UMAGMA_PEDANTIC -O3' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-8 FLAGS='-DMAGMA_PEDANTIC -O0' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-8 FLAGS='-DMAGMA_PEDANTIC -O2' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-8 FLAGS='-DMAGMA_PEDANTIC -O3' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-8 FLAGS='-UMAGMA_PEDANTIC -O0' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-8 FLAGS='-UMAGMA_PEDANTIC -O2' TARGET=all"
  - MATRIX_EVAL="COMPILER=gcc-8 FLAGS='-UMAGMA_PEDANTIC -O3' TARGET=all"
  - MATRIX_EVAL="COMPILER=clang-6.0 FLAGS='-DMAGMA_PEDANTIC -O0' TARGET='magmad magmad.check'"
  - MATRIX_EVAL="COMPILER=clang-6.0 FLAGS='-DMAGMA_PEDANTIC -O2' TARGET='magmad magmad.check'"
  - MATRIX_EVAL="COMPILER=clang-6.0 FLAGS='-DMAGMA_PEDANTIC -O3' TARGET='magmad magmad.check'"
  - MATRIX_EVAL="COMPILER=clang-6.0 FLAGS='-UMAGMA_PEDANTIC -O0' TARGET='magmad magmad.check'"
  - MATRIX_EVAL="COMPILER=clang-6.0 FLAGS='-UMAGMA_PEDANTIC -O2' TARGET='magmad magmad.check'"
  - MATRIX_EVAL="COMPILER=clang-6.0 FLAGS='-UMAGMA_PEDANTIC -O3' TARGET='magmad magmad.check'"
addons:
  apt:
    config:
      retries: true
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - autoconf
      - automake
      - bison
      - build-essential
      - cmake
      - curl
      - flex
      - gdb
      - git
      - git-man
      - gnupg
      - ibc++-dev
      - inotify-tools
      - libarchive13
      - libbsd-dev
      - libc6-dev
      - libmpfr4
      - libmpfr-dev
      - libncurses5-dev
      - libpython2.7
      - libsubunit0
      - libsubunit-dev
      - libtool
      - lsof
      - make
      - mlocate
      - patch
      - pciutils
      - pkg-config
      - postfix
      - rsync
      - sysstat
      - usbutils
      - valgrind
      - valgrind-dbg
      - wget
      - gcc-4.8
      - g++-4.8
      - gcc-4.8-locales
      - gcc-4.8-multilib
      - g++-4.8-multilib
      - libstdc++-4.8-dev
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-locales
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - libstdc++-4.9-dev
      - gcc-5
      - g++-5
      - gcc-5-locales
      - gcc-5-multilib
      - g++-5-multilib
      - libstdc++-5-dev
      - gcc-6
      - g++-6
      - gcc-6-locales
      - gcc-6-multilib
      - g++-6-multilib
      - libstdc++-6-dev
      - gcc-7
      - g++-7
      - gcc-7-locales
      - gcc-7-multilib
      - g++-7-multilib
      - libstdc++-7-dev
      - gcc-8
      - g++-8
      - gcc-8-locales
      - gcc-8-multilib
      - g++-8-multilib
      - libstdc++-8-dev
      - clang-6.0
      - llvm-6.0-dev
before_install:
  - eval "${MATRIX_EVAL}"
before_script:
  - export HOSTNAME=`hostname`
  - mysql -e "CREATE DATABASE Sandbox;"
  - mysql -e "CREATE USER 'mytool'@'localhost' IDENTIFIED BY 'aComplex1';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mytool'@'localhost' WITH GRANT OPTION;"
  - cd $HOME && curl --location --output util-linux-2.25.2.tar.gz https://www.kernel.org/pub/linux/utils/util-linux/v2.25/util-linux-2.25.2.tar.gz
  - tar xzf util-linux-2.25.2.tar.gz && cd util-linux-2.25.2
  - ./configure ADJTIME_PATH=/var/lib/hwclock/adjtime --disable-chfn-chsh --disable-login --disable-nologin --disable-su --disable-setpriv --disable-runuser --disable-pylibmount --disable-static --without-python --without-systemd --without-systemdsystemunitdir --without-ncurses
  - make prlimit && install --verbose --directory $HOME/bin/ && install --verbose --mode=755 prlimit $HOME/bin/prlimit && cd $TRAVIS_BUILD_DIR
script:
  - export HOSTNAME=`hostname`
  - export HASH=`git show  --quiet | grep commit | awk -F' ' '{print $2}'`
  - git remote add upstream https://github.com/lavabit/magma.git
  - git fetch upstream
  - git reset --hard upstream/develop
  - git checkout $HASH -- .travis.yml
  - sudo -E $HOME/bin/prlimit --pid "$$" --stack=unlimited:unlimited;
  - sudo -E $HOME/bin/prlimit --pid "$$" --memlock=unlimited:unlimited;
  - (for ((i = 0; i < 60; ++i)); do sleep 60 ; date ; done) & LOOP_PID=$! ; disown
  - dev/scripts/builders/build.lib.sh extract
  - dev/scripts/builders/build.lib.sh prep
  - M_CFLAGS="$FLAGS" M_CPPFLAGS="$FLAGS" M_CXXFLAGS="$FLAGS" dev/scripts/builders/build.lib.sh build
  - (dev/scripts/freshen/freshen.clamav.sh &> /dev/null) &
  - dev/scripts/builders/build.lib.sh combine
  - if [ ! -f magmad.so ]; then dev/scripts/builders/build.lib.sh mysql-log | tail -20; dev/scripts/builders/build.lib.sh jansson-log | tail -50; exit 1; fi
  - dev/scripts/builders/build.lib.sh load
  - dev/scripts/database/schema.reset.sh
  - kill $LOOP_PID
  - sed -i -e "/magma.iface.database.socket_path/d" sandbox/etc/magma.sandbox.config
  - sed -i -e "/magma.iface.database.host/d" sandbox/etc/magma.sandbox.config
  - sed -i -e "/magma.library.file/d" sandbox/etc/magma.sandbox.config
  - sed -i -e "/magma.spool/d" sandbox/etc/magma.sandbox.config
  - printf "magma.library.file = $TRAVIS_BUILD_DIR/magmad.so\n" >> sandbox/etc/magma.sandbox.config
  - printf "magma.iface.database.host = 127.0.0.1\n" >> sandbox/etc/magma.sandbox.config
  - printf "magma.secure.memory.enable = true\n" >> sandbox/etc/magma.sandbox.config
  - printf "magma.spool = /tmp/\n" >> sandbox/etc/magma.sandbox.config
  - chmod 700 sandbox/etc/tls.localhost.localdomain.pem
  - chmod 700 sandbox/etc/dkim.localhost.localdomain.pem
  - chmod 700 sandbox/etc/dime.localhost.localdomain.key
  - chmod 700 sandbox/etc/dime.localhost.localdomain.signet
  - CC="$COMPILER" CFLAGS="$FLAGS" make --keep-going --jobs=4 $TARGET && dev/scripts/launch/check.run.sh
